on:
  push:
    branches:
    - master

jobs:
  doxygen:
    name: Install doxygen
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: 'Doxygen'
