name: Build Template

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get short SHA
        uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6
      
      - name: Set short SHA
        run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
    
      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '10-2020-q4'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
  
      - name: PIP Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: pros-cli
  
      - name: Testing PROS Install 
        run: pros --version

      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Get version number
        id: get-version
        run: |
          version=$(awk -F'=' '/^VERSION:=/{print $2}' Makefile)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Update version in Makefile
        run: sed -i "s/^VERSION:=.*\$/VERSION:=${{ steps.get-version.outputs.version }}-c${{ env.SHA }}/" Makefile

      - name: Build PROS Project  
        run: pros make clean all

      - name: Create LemLib template
        run: pros make template

      - name: Create template folder
        run: mkdir template

      - name: Unzip Template
        uses: montudor/action-zip@v1.0.0
        with:
          args: unzip "LemLib@${{ steps.get-version.outputs.version }}-c${{ env.SHA }}.zip" -d template
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LemLib@${{ steps.get-version.outputs.version }}-c${{ env.SHA }}
          path: 'template/*'
          retention-days: 89
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq -y
      - name: Get Artifact URL
        id: get-artifact-url
        run: |
          ARTIFACT_URL=$(curl -s "https://api.github.com/repos/${{github.repository}}/actions/runs/${{ github.run_id }}/artifacts" | jq '.artifacts[0].archive_download_url')
          echo "Artifact URL: $ARTIFACT_URL"
          echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_OUTPUT
      - name: Use Artifact URL
        run: |
          echo "Artifact URL from previous step: ${{ steps.get-artifact-url.outputs.artifact_url }}"